# Generated by Django 3.1.7 on 2021-03-31 11:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='family/')),
            ],
            options={
                'verbose_name': 'family',
                'verbose_name_plural': 'family',
            },
        ),
    ]
