# Generated by Django 3.1.5 on 2021-01-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muslim_school', '0002_applicationform_calender_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='Calender_pdf',
            new_name='calender_pdf',
        ),
    ]
