# Generated by Django 3.1.5 on 2021-01-27 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muslim_school', '0004_remove_welcome_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calender',
            new_name='Staff',
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'staff', 'verbose_name_plural': 'staff'},
        ),
    ]
