# Generated by Django 3.1.5 on 2021-01-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muslim_school', '0005_auto_20210127_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Heading_three',
                'verbose_name_plural': 'Heading_three',
            },
        ),
        migrations.DeleteModel(
            name='HeaderThree',
        ),
        migrations.RemoveField(
            model_name='headerone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='headertwo',
            name='image',
        ),
    ]
