# Generated by Django 3.1.5 on 2021-01-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muslim_school', '0006_auto_20210127_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
