# Generated by Django 3.0.6 on 2021-03-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muslim_school', '0007_delete_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'verbose_name': 'pdf file', 'verbose_name_plural': 'pdf file'},
        ),
        migrations.RenameField(
            model_name='applicationform',
            old_name='application_form',
            new_name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='calender_pdf',
        ),
    ]
