# Generated by Django 3.0.6 on 2021-03-28 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muslim_school', '0008_auto_20210328_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'verbose_name': 'Application form', 'verbose_name_plural': 'Application forms'},
        ),
        migrations.RenameField(
            model_name='applicationform',
            old_name='pdf_file',
            new_name='application_form',
        ),
    ]
