# Generated by Django 3.1.7 on 2021-04-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='author',
        ),
        migrations.RemoveField(
            model_name='letters',
            name='timestamp',
        ),
    ]
