# Generated by Django 3.1.7 on 2021-04-01 12:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_letters_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letters',
            options={'verbose_name': 'admission', 'verbose_name_plural': 'admission'},
        ),
        migrations.RemoveField(
            model_name='letters',
            name='next_letters',
        ),
        migrations.RemoveField(
            model_name='letters',
            name='previous_letters',
        ),
        migrations.AlterField(
            model_name='letters',
            name='content',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='letters',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admission/'),
        ),
        migrations.AlterField(
            model_name='letters',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
