# Generated by Django 3.1.5 on 2021-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='next_post',
            new_name='next_library',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='previous_post',
            new_name='previous_library',
        ),
        migrations.AddField(
            model_name='library',
            name='application_form',
            field=models.FileField(blank=True, upload_to='library'),
        ),
    ]
