# Generated by Django 3.1.5 on 2021-01-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0002_auto_20210127_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='application_form',
        ),
        migrations.AddField(
            model_name='library',
            name='upload_book',
            field=models.FileField(blank=True, upload_to='library/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, upload_to='library/'),
        ),
    ]
