# Generated by Django 3.1.5 on 2021-01-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('application_form', models.FileField(blank=True, upload_to='Application')),
            ],
            options={
                'verbose_name': 'Application form',
                'verbose_name_plural': 'Application forms',
            },
        ),
        migrations.CreateModel(
            name='LatestProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
            ],
            options={
                'verbose_name': 'services',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='home_page/')),
            ],
            options={
                'verbose_name': 'services',
                'verbose_name_plural': 'services',
            },
        ),
        migrations.CreateModel(
            name='WelcomeWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='home_page/')),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'about us',
            },
        ),
    ]
