# Generated by Django 3.1.5 on 2021-01-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_page/')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'sliders',
            },
        ),
        migrations.AlterModelOptions(
            name='latestprojects',
            options={'verbose_name': 'latest projects', 'verbose_name_plural': 'latest projects'},
        ),
        migrations.AlterModelOptions(
            name='missionvision',
            options={'verbose_name': 'mission vision', 'verbose_name_plural': 'mission vision'},
        ),
        migrations.AlterModelOptions(
            name='welcomewords',
            options={'verbose_name': 'welcome word', 'verbose_name_plural': 'welcome words'},
        ),
        migrations.AlterField(
            model_name='latestprojects',
            name='image',
            field=models.ImageField(upload_to='home_page/'),
        ),
    ]
