# Generated by Django 3.1.5 on 2021-01-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20210110_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
