# Generated by Django 3.1.5 on 2021-01-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_slider_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionvision',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='missionvision',
            name='image',
        ),
    ]
