# Generated by Django 3.1.5 on 2021-01-28 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_auto_20210113_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestProjects',
        ),
    ]
