# Generated by Django 3.1.7 on 2021-03-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_delete_latestprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvision',
            name='image',
            field=models.ImageField(blank=True, upload_to='home_page/'),
        ),
    ]
